custom:
  cluster-props: &cluster-props
    spark_version: !ENV ${SPARK_VERSION}

  cluster: &cluster
    new_cluster:
      <<: *cluster-props
      policy_name: !ENV ${POLICY_NAME}

environments:
  staging:
    strict_path_adjustment_policy: true
    jobs:
      - name: sample_job
        <<:
          - *cluster
        spark_python_task:
          python_file: "file://dbx_config/jobs/opsguru/sample_job.py"
          parameters: ["--conf-file", "file:fuse://dbx_config/jobs/opsguru/conf/test/sample.yml"]
      - name: "sample_job_test"
        <<:
          - *cluster
        spark_python_task:
          python_file: "file://dbx_config/jobs/opsguru/tests/integration/sample_job.py"
          parameters: ["--conf-file", "file:fuse://dbx_config/jobs/opsguru/conf/test/sample.yml"]